---
- name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx
    - name: Copy file
      ansible.builtin.copy:
        src: ./main.html
        dest: /usr/share/nginx/html    

  handlers:
    - name: start nginx
      service:
        name: nginx
        state: started
